# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 856c6ade54fa035cf2daa8ddd6e8134eabbb05dc5d34a3bd71392205484f16671201d1255688c5d28a0d28934dcca1337ff2b14c6f5192ce736a4e450865d763

test:
  secret_key_base: 401d911e0bf2d9ba16f3ebd5b723db6ce2682e8e80ae826656a1d6bfaf0918ab045ba358f9c5db608f8f14ee5ec7191cd38ec9bd24df9f5fd5dc9f5195da879b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
